FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine3.17 as build
WORKDIR /src
COPY . .
RUN dotnet restore "CattleInformationSystem/CattleInformationSystem.sln"
RUN dotnet publish "CattleInformationSystem/src/CattleInformationSystem.Api/CattleInformationSystem.Api.csproj" -c Release -o /src/published-app

FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine3.17 as runtime
WORKDIR /app
COPY --from=build /src/published-app /app
ENTRYPOINT [ "dotnet", "/app/CattleInformationSystem.Api.dll" ]
