// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CattleInformationSystem.Animals.Specs
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AnimalEventsFeature : object, Xunit.IClassFixture<AnimalEventsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AnimalEvents.feature"
#line hidden
        
        public AnimalEventsFeature(AnimalEventsFeature.FixtureData fixtureData, CattleInformationSystem_Animals_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "Animal Events", "Fake events to test the animal processing. The life number will be generated!", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A newborn female on a milk breeding farm")]
        [Xunit.TraitAttribute("FeatureTitle", "Animal Events")]
        [Xunit.TraitAttribute("Description", "A newborn female on a milk breeding farm")]
        public void ANewbornFemaleOnAMilkBreedingFarm()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A newborn female on a milk breeding farm", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Gender",
                            "DateOfBirth",
                            "Reason",
                            "CurrentUbn",
                            "TargetUbn",
                            "EventDate"});
                table1.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Birth",
                            "20000000001",
                            "",
                            "2017-03-23"});
#line 5
        testRunner.Given("the following event(s)", ((string)(null)), table1, "Given ");
#line hidden
#line 8
        testRunner.When("added to the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
        testRunner.Then("it will be processed and added to the legacy database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A newborn female on a milk farm, dying the next day")]
        [Xunit.TraitAttribute("FeatureTitle", "Animal Events")]
        [Xunit.TraitAttribute("Description", "A newborn female on a milk farm, dying the next day")]
        public void ANewbornFemaleOnAMilkFarmDyingTheNextDay()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A newborn female on a milk farm, dying the next day", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Gender",
                            "DateOfBirth",
                            "Reason",
                            "CurrentUbn",
                            "TargetUbn",
                            "EventDate"});
                table2.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Birth",
                            "20000000001",
                            "",
                            "2017-03-23"});
                table2.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Death",
                            "20000000001",
                            "",
                            "2017-03-24"});
#line 12
        testRunner.Given("the following event(s)", ((string)(null)), table2, "Given ");
#line hidden
#line 16
        testRunner.When("added to the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
        testRunner.Then("it will be processed and added to the legacy database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A newborn female on a milk farm, dying the same day")]
        [Xunit.TraitAttribute("FeatureTitle", "Animal Events")]
        [Xunit.TraitAttribute("Description", "A newborn female on a milk farm, dying the same day")]
        public void ANewbornFemaleOnAMilkFarmDyingTheSameDay()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A newborn female on a milk farm, dying the same day", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Gender",
                            "DateOfBirth",
                            "Reason",
                            "CurrentUbn",
                            "TargetUbn",
                            "EventDate"});
                table3.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Birth",
                            "20000000001",
                            "",
                            "2017-03-23"});
                table3.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Death",
                            "20000000001",
                            "",
                            "2017-03-23"});
#line 20
        testRunner.Given("the following event(s)", ((string)(null)), table3, "Given ");
#line hidden
#line 24
        testRunner.When("added to the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
        testRunner.Then("it will be processed and added to the legacy database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A newborn female on a milk breeding farm, giving birth after 3 years")]
        [Xunit.TraitAttribute("FeatureTitle", "Animal Events")]
        [Xunit.TraitAttribute("Description", "A newborn female on a milk breeding farm, giving birth after 3 years")]
        public void ANewbornFemaleOnAMilkBreedingFarmGivingBirthAfter3Years()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A newborn female on a milk breeding farm, giving birth after 3 years", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Gender",
                            "DateOfBirth",
                            "Reason",
                            "CurrentUbn",
                            "TargetUbn",
                            "EventDate"});
                table4.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Birth",
                            "20000000001",
                            "",
                            "2017-03-23"});
                table4.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Calved",
                            "20000000001",
                            "",
                            "2020-02-20"});
#line 28
        testRunner.Given("the following event(s)", ((string)(null)), table4, "Given ");
#line hidden
#line 32
        testRunner.When("added to the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
        testRunner.Then("it will be processed and added to the legacy database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="A newborn male on a milk farm")]
        [Xunit.TraitAttribute("FeatureTitle", "Animal Events")]
        [Xunit.TraitAttribute("Description", "A newborn male on a milk farm")]
        public void ANewbornMaleOnAMilkFarm()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A newborn male on a milk farm", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Gender",
                            "DateOfBirth",
                            "Reason",
                            "CurrentUbn",
                            "TargetUbn",
                            "EventDate"});
                table5.AddRow(new string[] {
                            "Male",
                            "2017-03-23",
                            "Birth",
                            "20000000001",
                            "",
                            "2023-05-23"});
#line 36
        testRunner.Given("the following event(s)", ((string)(null)), table5, "Given ");
#line hidden
#line 39
        testRunner.When("added to the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
        testRunner.Then("it will be processed and added to the legacy database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="The full history of a female cow")]
        [Xunit.TraitAttribute("FeatureTitle", "Animal Events")]
        [Xunit.TraitAttribute("Description", "The full history of a female cow")]
        public void TheFullHistoryOfAFemaleCow()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The full history of a female cow", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Gender",
                            "DateOfBirth",
                            "Reason",
                            "CurrentUbn",
                            "TargetUbn",
                            "EventDate"});
                table6.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Birth",
                            "20000000001",
                            "",
                            "2017-03-23"});
                table6.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Departure",
                            "20000000001",
                            "20000000002",
                            "2017-06-24"});
                table6.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Arrival",
                            "20000000005",
                            "",
                            "2017-06-24"});
                table6.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Departure",
                            "20000000005",
                            "20000000006",
                            "2019-04-02"});
                table6.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Arrival",
                            "20000000006",
                            "20000000009",
                            "2019-04-02"});
                table6.AddRow(new string[] {
                            "Female",
                            "2017-03-23",
                            "Death",
                            "20000000009",
                            "",
                            "2019-04-02"});
#line 43
        testRunner.Given("the following event(s)", ((string)(null)), table6, "Given ");
#line hidden
#line 51
        testRunner.When("added to the queue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 52
        testRunner.Then("it will be processed and added to the legacy database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AnimalEventsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AnimalEventsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
